sequenceDiagram
    participant User
    participant Main as main()
    participant Logger as Logger
    participant FileDataExtractor as FileDataExtractor
    participant House as House
    participant VacuumCleaner as VacuumCleaner
    participant Controller as Controller

    User ->> Main: Start program with input file argument
    Main ->> Logger: getInstance()
    Logger ->> Main: logger
    Main ->> Logger: logInfo("Starting the program with file: " + fileName)
    Main ->> FileDataExtractor: readAndExtract(fileName)
    FileDataExtractor -->> Main: Extraction results

    Main ->> House: House(inputData.getHouseMap(), dockingX, dockingY)
    Main ->> VacuumCleaner: VacuumCleaner(dockingX, dockingY, inputData.getMaxBatterySteps())
    Main ->> Controller: Controller(house, vacuumCleaner, inputData.getMaxSteps())
    
    Main ->> Controller: run()
    Controller ->> Logger: logInfo("Starting vacuum cleaner")
    
    loop Until missionCompleted or missionFailed
        Controller ->> House: getTotalDirt()
        Controller ->> VacuumCleaner: getBatteryLevel()
        Controller ->> VacuumCleaner: getLocation(currentVacuumLocation)
        Controller ->> Logger: logInfo("Step details...")
        alt House.getTotalDirt() == 0 and atDockingStation
            Controller ->> Controller: missionCompleted = true
            %% break
        end
        alt (currentBatteryLevel == 0 and !atDockingStation) or maxSteps - stepsTaken == 0
            Controller ->> Controller: missionFailed = true
            %% break
        end
        alt currentBatteryLevel < VacuumCleaner.getMaxBatterySteps() and atDockingStation
            Controller ->> VacuumCleaner: increaseChargeBy(1)
            Controller ->> Controller: stepsTaken++
            Controller ->> Controller: steps.push_back(STAY)
        else
            Controller ->> Algorithm: decideNextStep()
            Algorithm -->> Controller: nextStep
            Controller ->> VacuumCleaner: move(nextStep)
            Controller ->> House: decreaseDirtLevel(vacuumCleanerLocation, 1)
            Controller ->> VacuumCleaner: decreaseChargeBy(1)
            Controller ->> VacuumCleaner: getLocation(vacuumCleanerLocation)
            alt Config::getInstance().get("useVisualizer") == "true"
                Controller ->> House: houseVisualization(vacuumCleanerLocation)
            end
        end
    end
    Controller ->> Config: getInstance().get("outputFileName")
    Config ->> Controller: outputFileName
    Controller ->> Controller: createOutputFile(outputFileName)
    Controller ->> Main: Finished
    Main ->> Logger: logInfo("Program finished successfully")
